CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --do_predict \
    --model_name_or_path meta-llama/Llama-2-7b-hf \
    --adapter_name_or_path saves/Llama-2-7b-hf/animal_train/sft \
    --dataset animal_train,animal_test \
    --dataset_dir data \
    --template llama2 \
    --finetuning_type lora \
    --output_dir saves/Llama-2-7b-hf/animal_train/sft/predict \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 1024 \
    --preprocessing_num_workers 16 \
    --per_device_eval_batch_size 1 \
    --predict_with_generate